version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_GH_2711Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: substractpackage
  gitServerName: src_shared_GitLabCtrl_Arti
  gitUrl: https://gitlab.com/ArtiKhareGitlabnew
  gitUsername: ArtiKhareGitlabnew
  gitBranch: master
